let shopItemsData = [
  {
    id: "thierytbvcbvzdhadjk",
    name: "Sequin Party Dress",
    price: 5000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../assets/images/special-dish-banner.jpg",
  },
  {
    id: "jfhgbvnscs",
    name: "White T-Shirt",
    price: 500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../assets/images/menu-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Check Shirt",
    price: 800,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../assets/images/menu-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Sundress",
    price: 3000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../assets/images/menu-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mini Prom",
    price: 5000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../assets/images/menu-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Skirt",
    price: 750,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../assets/images/menu-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Summer Set",
    price: 1500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../assets/images/menu-6.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "polo shirt",
    price: 1050,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 850,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "denim pants",
    price: 1200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "basic cap",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "leather boots",
    price: 3500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-12.png",
  },
];
